// You can add new scenarios, but make sure that there is exactly...
// * 1 hackerCard per scenario
// * 3 playerCards per scenario

var scenarios = [
  {hackerCard: {description: '100 * 20 equals to: ', power: 4}, playerCards: [{description: '2000', power: 5}, {description: '2006', power: 3}, {description: '2007', power: 1}]},
  {hackerCard: {description: '42 - 2 equals to: ', power: 4}, playerCards: [{description: '40', power: 5}, {description: '42', power: 3}, {description: '65', power: 1}]},
  {hackerCard: {description: '66 + 5 equals to: ', power: 4}, playerCards: [{description: '71', power: 5}, {description: '84', power: 3}, {description: '75', power: 1}]},
  {hackerCard: {description: '50 + 67 equals to: ', power: 4}, playerCards: [{description: '117', power: 5}, {description: '125', power: 3}, {description: '130', power: 1}]},
  {hackerCard: {description: '91 * 55 equals to: ', power: 4}, playerCards: [{description: '5005', power: 5}, {description: '5008', power: 3}, {description: '5027', power: 1}]},
  {hackerCard: {description: '34 + 27 equals to: ', power: 4}, playerCards: [{description: '61', power: 5}, {description: '73', power: 3}, {description: '64', power: 1}]},
  {hackerCard: {description: '88 + 24 equals to: ', power: 4}, playerCards: [{description: '112', power: 5}, {description: '123', power: 3}, {description: '121', power: 1}]},
  {hackerCard: {description: '95 * 37 equals to: ', power: 4}, playerCards: [{description: '3515', power: 5}, {description: '3519', power: 3}, {description: '3535', power: 1}]},
  {hackerCard: {description: '61 * 9 equals to: ', power: 4}, playerCards: [{description: '549', power: 5}, {description: '555', power: 3}, {description: '566', power: 1}]},
  {hackerCard: {description: '48 - 2 equals to: ', power: 4}, playerCards: [{description: '46', power: 5}, {description: '52', power: 3}, {description: '48', power: 1}]},
  {hackerCard: {description: '95 * 14 equals to: ', power: 4}, playerCards: [{description: '1330', power: 5}, {description: '1334', power: 3}, {description: '1340', power: 1}]},
  {hackerCard: {description: '90 - 23 equals to: ', power: 4}, playerCards: [{description: '67', power: 5}, {description: '72', power: 3}, {description: '74', power: 1}]},
  {hackerCard: {description: '9 + 24 equals to: ', power: 4}, playerCards: [{description: '33', power: 5}, {description: '44', power: 3}, {description: '56', power: 1}]},
  {hackerCard: {description: '54 * 48 equals to: ', power: 4}, playerCards: [{description: '2592', power: 5}, {description: '2595', power: 3}, {description: '2615', power: 1}]},
  {hackerCard: {description: '92 + 78 equals to: ', power: 4}, playerCards: [{description: '170', power: 5}, {description: '183', power: 3}, {description: '174', power: 1}]},
  {hackerCard: {description: '28 * 100 equals to: ', power: 4}, playerCards: [{description: '2800', power: 5}, {description: '2808', power: 3}, {description: '2819', power: 1}]},
  {hackerCard: {description: '90 - 16 equals to: ', power: 4}, playerCards: [{description: '74', power: 5}, {description: '84', power: 3}, {description: '81', power: 1}]},
  {hackerCard: {description: '55 + 95 equals to: ', power: 4}, playerCards: [{description: '150', power: 5}, {description: '155', power: 3}, {description: '165', power: 1}]},
  {hackerCard: {description: '95 + 90 equals to: ', power: 4}, playerCards: [{description: '185', power: 5}, {description: '189', power: 3}, {description: '198', power: 1}]},
  {hackerCard: {description: '50 * 97 equals to: ', power: 4}, playerCards: [{description: '4850', power: 5}, {description: '4862', power: 3}, {description: '4863', power: 1}]},
  {hackerCard: {description: '64 * 48 equals to: ', power: 4}, playerCards: [{description: '3072', power: 5}, {description: '3075', power: 3}, {description: '3097', power: 1}]},
  {hackerCard: {description: '74 * 49 equals to: ', power: 4}, playerCards: [{description: '3626', power: 5}, {description: '3629', power: 3}, {description: '3643', power: 1}]},
  {hackerCard: {description: '97 + 83 equals to: ', power: 4}, playerCards: [{description: '180', power: 5}, {description: '193', power: 3}, {description: '196', power: 1}]},
  {hackerCard: {description: '94 - 49 equals to: ', power: 4}, playerCards: [{description: '45', power: 5}, {description: '49', power: 3}, {description: '68', power: 1}]},
  {hackerCard: {description: '56 * 99 equals to: ', power: 4}, playerCards: [{description: '5544', power: 5}, {description: '5547', power: 3}, {description: '5566', power: 1}]},
  {hackerCard: {description: '24 + 34 equals to: ', power: 4}, playerCards: [{description: '58', power: 5}, {description: '69', power: 3}, {description: '79', power: 1}]},
  {hackerCard: {description: '17 - 76 equals to: ', power: 4}, playerCards: [{description: '-59', power: 5}, {description: '-47', power: 3}, {description: '-49', power: 1}]},
  {hackerCard: {description: '72 * 75 equals to: ', power: 4}, playerCards: [{description: '5400', power: 5}, {description: '5405', power: 3}, {description: '5408', power: 1}]},
  {hackerCard: {description: '31 * 33 equals to: ', power: 4}, playerCards: [{description: '1023', power: 5}, {description: '1033', power: 3}, {description: '1042', power: 1}]},
  {hackerCard: {description: '9 + 56 equals to: ', power: 4}, playerCards: [{description: '65', power: 5}, {description: '73', power: 3}, {description: '71', power: 1}]},
  {hackerCard: {description: '56 + 71 equals to: ', power: 4}, playerCards: [{description: '127', power: 5}, {description: '135', power: 3}, {description: '141', power: 1}]},
  {hackerCard: {description: '96 * 23 equals to: ', power: 4}, playerCards: [{description: '2208', power: 5}, {description: '2210', power: 3}, {description: '2214', power: 1}]},
  {hackerCard: {description: '15 - 67 equals to: ', power: 4}, playerCards: [{description: '-52', power: 5}, {description: '-45', power: 3}, {description: '-43', power: 1}]},
  {hackerCard: {description: '59 * 49 equals to: ', power: 4}, playerCards: [{description: '2891', power: 5}, {description: '2899', power: 3}, {description: '2900', power: 1}]},
  {hackerCard: {description: '8 * 42 equals to: ', power: 4}, playerCards: [{description: '336', power: 5}, {description: '342', power: 3}, {description: '338', power: 1}]},
  {hackerCard: {description: '48 * 56 equals to: ', power: 4}, playerCards: [{description: '2688', power: 5}, {description: '2694', power: 3}, {description: '2695', power: 1}]},
  {hackerCard: {description: '56 + 72 equals to: ', power: 4}, playerCards: [{description: '128', power: 5}, {description: '140', power: 3}, {description: '138', power: 1}]},
  {hackerCard: {description: '79 * 67 equals to: ', power: 4}, playerCards: [{description: '5293', power: 5}, {description: '5299', power: 3}, {description: '5314', power: 1}]},
  {hackerCard: {description: '71 * 87 equals to: ', power: 4}, playerCards: [{description: '6177', power: 5}, {description: '6179', power: 3}, {description: '6184', power: 1}]},
  {hackerCard: {description: '21 - 88 equals to: ', power: 4}, playerCards: [{description: '-67', power: 5}, {description: '-64', power: 3}, {description: '-53', power: 1}]},
  {hackerCard: {description: '81 * 18 equals to: ', power: 4}, playerCards: [{description: '1458', power: 5}, {description: '1464', power: 3}, {description: '1480', power: 1}]},
  {hackerCard: {description: '88 + 91 equals to: ', power: 4}, playerCards: [{description: '179', power: 5}, {description: '183', power: 3}, {description: '205', power: 1}]},
  {hackerCard: {description: '44 * 33 equals to: ', power: 4}, playerCards: [{description: '1452', power: 5}, {description: '1462', power: 3}, {description: '1464', power: 1}]},
  {hackerCard: {description: '99 + 87 equals to: ', power: 4}, playerCards: [{description: '186', power: 5}, {description: '199', power: 3}, {description: '207', power: 1}]},
  {hackerCard: {description: '47 - 30 equals to: ', power: 4}, playerCards: [{description: '17', power: 5}, {description: '29', power: 3}, {description: '20', power: 1}]},
  {hackerCard: {description: '83 * 11 equals to: ', power: 4}, playerCards: [{description: '913', power: 5}, {description: '925', power: 3}, {description: '923', power: 1}]},
  {hackerCard: {description: '31 - 49 equals to: ', power: 4}, playerCards: [{description: '-18', power: 5}, {description: '-9', power: 3}, {description: '-3', power: 1}]},
  {hackerCard: {description: '16 * 92 equals to: ', power: 4}, playerCards: [{description: '1472', power: 5}, {description: '1482', power: 3}, {description: '1489', power: 1}]},
  {hackerCard: {description: '34 + 32 equals to: ', power: 4}, playerCards: [{description: '66', power: 5}, {description: '72', power: 3}, {description: '92', power: 1}]},
  {hackerCard: {description: '1 - 67 equals to: ', power: 4}, playerCards: [{description: '-66', power: 5}, {description: '-58', power: 3}, {description: '-40', power: 1}]}
];