// You can add new scenarios, but make sure that there is exactly...
// * 1 hackerCard per scenario
// * 3 playerCards per scenario

var scenarios = [
  {hackerCard: {description: '41 * 22 equals to: ', power: 4}, playerCards: [{description: '902', power: 5}, {description: '906', power: 3}, {description: '917', power: 1}]},
  {hackerCard: {description: '52 * 29 equals to: ', power: 4}, playerCards: [{description: '1508', power: 5}, {description:'1518', power: 3}, {description: '1508', power: 1}]},
  {hackerCard: {description: '13 - 83 equals to: ', power: 4}, playerCards: [{description: '-70', power: 5}, {description: '-57', power: 3}, {description: '-65', power: 1}]},
  {hackerCard: {description: '10 - 7 equals to: ', power: 4}, playerCards: [{description: '3', power: 5}, {description: '15', power: 3}, {description: '13', power: 1}]},
  {hackerCard: {description: '67 - 25 equals to: ', power: 4}, playerCards: [{description: '42', power: 5}, {description: '44', power: 3}, {description: '51', power: 1}]},
  {hackerCard: {description: '86 + 83 equals to: ', power: 4}, playerCards: [{description: '169', power: 5}, {description: '181', power: 3}, {description: '188', power: 1}]},
  {hackerCard: {description: '70 - 49 equals to: ', power: 4}, playerCards: [{description: '21', power: 5}, {description: '29', power: 3}, {description: '35', power: 1}]},
  {hackerCard: {description: '41 * 36 equals to: ', power: 4}, playerCards: [{description: '1476', power: 5}, {description:'1484', power: 3}, {description: '1486', power: 1}]},
  {hackerCard: {description: '41 - 35 equals to: ', power: 4}, playerCards: [{description: '6', power: 5}, {description: '17', power: 3}, {description: '6', power: 1}]},
  {hackerCard: {description: '53 - 67 equals to: ', power: 4}, playerCards: [{description: '-14', power: 5}, {description: '-2', power: 3}, {description: '4', power: 1}]},
  {hackerCard: {description: '34 + 58 equals to: ', power: 4}, playerCards: [{description: '92', power: 5}, {description: '95', power: 3}, {description: '107', power: 1}]},
  {hackerCard: {description: '57 + 13 equals to: ', power: 4}, playerCards: [{description: '70', power: 5}, {description: '70', power: 3}, {description: '87', power: 1}]},
  {hackerCard: {description: '5 - 8 equals to: ', power: 4}, playerCards: [{description: '-3', power: 5}, {description: '6', power: 3}, {description: '5', power: 1}]},
  {hackerCard: {description: '74 - 14 equals to: ', power: 4}, playerCards: [{description: '60', power: 5}, {description: '60', power: 3}, {description: '66', power: 1}]},
  {hackerCard: {description: '5 - 44 equals to: ', power: 4}, playerCards: [{description: '-39', power: 5}, {description: '-35', power: 3}, {description: '-38', power: 1}]},
  {hackerCard: {description: '22 * 63 equals to: ', power: 4}, playerCards: [{description: '1386', power: 5}, {description:'1394', power: 3}, {description: '1396', power: 1}]},
  {hackerCard: {description: '42 + 48 equals to: ', power: 4}, playerCards: [{description: '90', power: 5}, {description: '101', power: 3}, {description: '111', power: 1}]},
  {hackerCard: {description: '96 * 74 equals to: ', power: 4}, playerCards: [{description: '7104', power: 5}, {description:'7113', power: 3}, {description: '7127', power: 1}]},
  {hackerCard: {description: '14 - 88 equals to: ', power: 4}, playerCards: [{description: '-74', power: 5}, {description: '-72', power: 3}, {description: '-49', power: 1}]},
  {hackerCard: {description: '46 - 40 equals to: ', power: 4}, playerCards: [{description: '6', power: 5}, {description: '8', power: 3}, {description: '30', power: 1}]},
  {hackerCard: {description: '17 - 41 equals to: ', power: 4}, playerCards: [{description: '-24', power: 5}, {description: '-18', power: 3}, {description: '2', power: 1}]},
  {hackerCard: {description: '69 + 19 equals to: ', power: 4}, playerCards: [{description: '88', power: 5}, {description: '90', power: 3}, {description: '115', power: 1}]},
  {hackerCard: {description: '34 + 59 equals to: ', power: 4}, playerCards: [{description: '93', power: 5}, {description: '103', power: 3}, {description: '102', power: 1}]},
  {hackerCard: {description: '1 * 64 equals to: ', power: 4}, playerCards: [{description: '64', power: 5}, {description: '66', power: 3}, {description: '78', power: 1}]},
  {hackerCard: {description: '50 - 54 equals to: ', power: 4}, playerCards: [{description: '-4', power: 5}, {description: '3', power: 3}, {description: '6', power: 1}]},
  {hackerCard: {description: '45 * 40 equals to: ', power: 4}, playerCards: [{description: '1800', power: 5}, {description:'1803', power: 3}, {description: '1814', power: 1}]},
  {hackerCard: {description: '71 - 82 equals to: ', power: 4}, playerCards: [{description: '-11', power: 5}, {description: '-5', power: 3}, {description: '-3', power: 1}]},
  {hackerCard: {description: '24 + 34 equals to: ', power: 4}, playerCards: [{description: '58', power: 5}, {description: '61', power: 3}, {description: '59', power: 1}]},
  {hackerCard: {description: '74 + 53 equals to: ', power: 4}, playerCards: [{description: '127', power: 5}, {description: '130', power: 3}, {description: '143', power: 1}]},
  {hackerCard: {description: '33 + 34 equals to: ', power: 4}, playerCards: [{description: '67', power: 5}, {description: '77', power: 3}, {description: '73', power: 1}]},
  {hackerCard: {description: '6 - 7 equals to: ', power: 4}, playerCards: [{description: '-1', power: 5}, {description: '9', power: 3}, {description: '20', power: 1}]},
  {hackerCard: {description: '14 + 19 equals to: ', power: 4}, playerCards: [{description: '33', power: 5}, {description: '34', power: 3}, {description: '44', power: 1}]},
  {hackerCard: {description: '1 * 49 equals to: ', power: 4}, playerCards: [{description: '49', power: 5}, {description: '58', power: 3}, {description: '71', power: 1}]},
  {hackerCard: {description: '30 * 38 equals to: ', power: 4}, playerCards: [{description: '1140', power: 5}, {description:'1151', power: 3}, {description: '1163', power: 1}]},
  {hackerCard: {description: '86 + 100 equals to: ', power: 4}, playerCards: [{description: '186', power: 5}, {description:'187', power: 3}, {description: '194', power: 1}]},
  {hackerCard: {description: '3 + 99 equals to: ', power: 4}, playerCards: [{description: '102', power: 5}, {description: '115', power: 3}, {description: '108', power: 1}]},
  {hackerCard: {description: '81 - 50 equals to: ', power: 4}, playerCards: [{description: '31', power: 5}, {description: '41', power: 3}, {description: '31', power: 1}]},
  {hackerCard: {description: '19 * 43 equals to: ', power: 4}, playerCards: [{description: '817', power: 5}, {description: '826', power: 3}, {description: '835', power: 1}]},
  {hackerCard: {description: '29 - 90 equals to: ', power: 4}, playerCards: [{description: '-61', power: 5}, {description: '-60', power: 3}, {description: '-38', power: 1}]},
  {hackerCard: {description: '47 - 78 equals to: ', power: 4}, playerCards: [{description: '-31', power: 5}, {description: '-29', power: 3}, {description: '-14', power: 1}]},
  {hackerCard: {description: '13 + 68 equals to: ', power: 4}, playerCards: [{description: '81', power: 5}, {description: '88', power: 3}, {description: '84', power: 1}]},
  {hackerCard: {description: '18 * 17 equals to: ', power: 4}, playerCards: [{description: '306', power: 5}, {description: '316', power: 3}, {description: '327', power: 1}]},
  {hackerCard: {description: '85 * 48 equals to: ', power: 4}, playerCards: [{description: '4080', power: 5}, {description:'4088', power: 3}, {description: '4105', power: 1}]},
  {hackerCard: {description: '65 * 30 equals to: ', power: 4}, playerCards: [{description: '1950', power: 5}, {description:'1953', power: 3}, {description: '1977', power: 1}]},
  {hackerCard: {description: '61 + 59 equals to: ', power: 4}, playerCards: [{description: '120', power: 5}, {description: '128', power: 3}, {description: '125', power: 1}]},
  {hackerCard: {description: '13 + 39 equals to: ', power: 4}, playerCards: [{description: '52', power: 5}, {description: '54', power: 3}, {description: '53', power: 1}]},
  {hackerCard: {description: '31 + 94 equals to: ', power: 4}, playerCards: [{description: '125', power: 5}, {description: '135', power: 3}, {description: '145', power: 1}]},
  {hackerCard: {description: '19 * 2 equals to: ', power: 4}, playerCards: [{description: '38', power: 5}, {description: '38', power: 3}, {description: '53', power: 1}]},
  {hackerCard: {description: '9 - 66 equals to: ', power: 4}, playerCards: [{description: '-57', power: 5}, {description: '-57', power: 3}, {description: '-44', power: 1}]},
  {hackerCard: {description: '16 - 84 equals to: ', power: 4}, playerCards: [{description: '-68', power: 5}, {description: '-56', power: 3}, {description: '-50', power: 1}]}
];